ingress:
  enabled: true
  path: /v1/(.*)
  pathType: ImplementationSpecific
  tls:
    secretName: schema-manager-be-tls
  ingressClass: nginx

serviceAccount:
  enabled: true
  name: simpl-schema-manager-service-account
