apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.chart_name }}-realms
data:
{{- if .Values.eidas.enabled }}
  authority-realm.json: |-
{{ .Files.Get "data/keycloak/authority-with-eidas.json" | indent 4 }}
  onboarding-realm.json: |-
{{ .Files.Get "data/keycloak/onboarding-with-eidas.json" | indent 4 }}
{{- else }}
  authority-realm.json: |-
{{ .Files.Get "data/keycloak/authority.json" | indent 4 }}
  onboarding-realm.json: |-
{{ .Files.Get "data/keycloak/onboarding.json" | indent 4 }}
{{- end }}
