agentList: {}

monorepo_URL: https://github.com/ForumViriumHelsinki/TFDS-SIMPL-open-helm-charts.git
monorepo_branch: main

project: ${PROJECT}
domainSuffix: ${DOMAINSUFFIX}
identifierNumber: ${IDENTIFIERNUMBER}
namespaceTag:
  authority: ${AUTHNAMESPACETAG}
  common: ${COMMONSPACETAG}

singleNode: true

resourcePreset: default
# resourcePreset: low

argocd:
  appname: ${NAMESPACE}
  namespace: ${ARGOCDNAMESPACE}

cluster:
  address: https://kubernetes.default.svc
  namespace: ${NAMESPACE}
  commonToolsNamespace: ${COMMONNAMESPACE}
  issuer: ${CLUSTERISSUER}

secrets:
  role: ${SECRETROLE}
  secretEngine: ${SECRETENGINE}

# ==========================================
# CONSOLIDATED LEVEL 2 BUNDLE: authority-iaa
# ==========================================
keycloak:
  enabled: true
  keycloak_authenticator:
  eidas_demo_keycloak_extension:
  nameOverride: keycloak
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "500m"
      memory: "1G"
    limits:
      cpu: "1"
      memory: "2G"
ejbca:
  enabled: true
  repo_URL: "https://registry.primekey.com/repository/helm-primekey-enterprise"
  targetRevision: 1.0.7
  chart_name: ejbca-community-helm
  fullnameOverride: ejbca-community-helm
  resources:
    requests:
      cpu: "500m"
      memory: "1024Mi"
    limits:
      cpu: "500m"
      memory: "1024Mi"
tier1_gateway:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
sap:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
users_roles:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
fe_auth_provider:
  enabled: true
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"
fe_users_roles:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
fe_identity_provider:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"
fe_security_attribute_provider:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

fe_onboarding:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

onboarding:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

tier2_gateway:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

identity_provider:
  enabled: true
  fullnameOverride: identity-provider
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

auth_provider:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "400Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
redis:
  enabled: true
  repo_URL: "https://charts.bitnami.com/bitnami"
  targetRevision: 19.6.0
  chart_name: redis
  nameOverride: redis
  resourcesPreset: "none"
  resources:
    requests:
      cpu: "0"
      memory: "0"
redis_commander:
  projectID: 1359
  targetRevision: 0.1.1
  chart_name: redis-commander

  enabled: false
  nameOverride: redis-commander
  path: "k8s/helm-chart/redis-commander"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
tier2_proxy:
  enabled: true
  resources:
    requests:
      cpu: "500m"
      memory: "500Mi"
    limits:
      cpu: "500m"
      memory: "500Mi"
# End services configuration

# Start development configuration
development:
  enableTestConfigurations: false
# End development configuration

# Start postgrest configuration
# Enabled by value [development.enableTestConfigurations]
postgrest:
  databases:
    - name: "authenticationprovider"
      host: "pg-cluster.{{ .Values.cluster.commonToolsNamespace }}.svc.cluster.local"
      port: "5432"
      database: "{{ .Values.cluster.namespace }}_authenticationprovider"
      user: "{{ .Values.namespaceTag.authority }}_authenticationprovider"
      password: "vault:{{ .Values.secrets.secretEngine }}/data/{{ .Values.cluster.namespace }}-postgres-passwords#{{ .Values.cluster.namespace }}-authenticationprovider"
      anonRole: "{{ .Values.namespaceTag.authority }}_authenticationprovider"
      dbPool: 1
    - name: identityprovider
      host: "pg-cluster.{{ .Values.cluster.commonToolsNamespace }}.svc.cluster.local"
      port: "5432"
      database: "{{ .Values.cluster.namespace }}_identityprovider"
      user: "{{ .Values.namespaceTag.authority }}_identityprovider"
      password: "vault:{{ .Values.secrets.secretEngine }}/data/{{ .Values.cluster.namespace }}-postgres-passwords#{{ .Values.cluster.namespace }}-identityprovider"
      anonRole: "{{ .Values.namespaceTag.authority }}_identityprovider"
      dbPool: 1
    - name: onboarding
      host: "pg-cluster.{{ .Values.cluster.commonToolsNamespace }}.svc.cluster.local"
      port: "5432"
      database: "{{ .Values.cluster.namespace }}_onboarding"
      user: "{{ .Values.namespaceTag.authority }}_onboarding"
      password: "vault:{{ .Values.secrets.secretEngine }}/data/{{ .Values.cluster.namespace }}-postgres-passwords#{{ .Values.cluster.namespace }}-onboarding"
      anonRole: "{{ .Values.namespaceTag.authority }}_onboarding"
      dbPool: 1
    - name: securityattributesprovider
      host: "pg-cluster.{{ .Values.cluster.commonToolsNamespace }}.svc.cluster.local"
      port: "5432"
      database: "{{ .Values.cluster.namespace }}_securityattributesprovider"
      user: "{{ .Values.namespaceTag.authority }}_securityattributesprovider"
      password: "vault:{{ .Values.secrets.secretEngine }}/data/{{ .Values.cluster.namespace }}-postgres-passwords#{{ .Values.cluster.namespace }}-securityattributesprovider"
      anonRole: "{{ .Values.namespaceTag.authority }}_securityattributesprovider"
      dbPool: 1
    - name: usersroles
      host: "pg-cluster.{{ .Values.cluster.commonToolsNamespace }}.svc.cluster.local"
      port: "5432"
      database: "{{ .Values.cluster.namespace }}_usersroles"
      user: "{{ .Values.namespaceTag.authority }}_usersroles"
      password: "vault:{{ .Values.secrets.secretEngine }}/data/{{ .Values.cluster.namespace }}-postgres-passwords#{{ .Values.cluster.namespace }}-usersroles"
      anonRole: "{{ .Values.namespaceTag.authority }}_usersroles"
      dbPool: 1
# End postgrest configuration

eidas:
  enabled: false
xsfc_catalogue:
  enabled: true
  resources:
    requests:
      cpu: "400m"
      memory: "512Mi"
    limits:
      cpu: "400m"
      memory: "512Mi"

adapter:
  enabled: true
  fullnameOverride: adapter

simpl_schema_manager:
  enabled: true
  fullnameOverride: simpl-schema-manager
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

simpl_schema_manager_ui:
  enabled: true
  fullnameOverride: simpl-schema-manager-ui
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

# ==========================================
# CONSOLIDATED LEVEL 2 BUNDLE: authority-monitoring
# ==========================================
monitoring:
  enabled: true
  fullnameOverride: elastic
  resources:
    filebeat:
      requests:
        memory: "100Mi"
        cpu: "100m"
