apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authority-deployer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ForumViriumHelsinki/TFDS_SIMPL-open_governance_authority.git"
    path: charts
    targetRevision: feature/v3.1.0
    helm:
      values: |
        values:
          branch: feature/v3.1.0                 # branch of repo with values - for released version it should be the release branch
        project: default
        namespaceTag:
          authority: authority
          common: common
        domainSuffix: ds.helsinki.tfds.io
        resourcePreset: low             # set to "low" to disable requests of resources
        argocd:
          appname: authority
          namespace: argocd
        cluster:
          address: https://kubernetes.default.svc
          namespace: authority
          commonToolsNamespace: common
          issuer: dev-prod
        secrets:
          role: example-role
          secretEngine: example
        authority_monitoring:
          enabled: false
        authority_iaa:
          extraValues:
            development:
              enableAutomaticInitialization: false
  destination:
    server: https://kubernetes.default.svc
    namespace: authority
