apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authority-deployer
spec:
  project: default
  source:
    repoURL: https://code.europa.eu/api/v4/projects/902/packages/helm/stable
    path: '""'
    targetRevision: 3.0.0-F-feature-splits.821.0312ac0c
    helm:
      values: |
        project: default
        namespaceTag: 
          authority: authority
          common: common
        domainSuffix: ds.helsinki.tfds.io
        organization:
          name: "FVH"
          unit: "Data"
          country: "FI"
        argocd:
          appname: authority
          namespace: argocd
        cluster:
          address: https://kubernetes.default.svc
          namespace: authority
          commonToolsNamespace: common
          issuer: dev-prod
        secrets:
          role: example-role
          secretEngine: example
        monitoring:
          enabled: false
        authority_iaa:
          extraValues:
            development:
              enableAutomaticInitialization: false
            keycloak:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
            ejbca-community-helm:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
            identity-provider:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
            authentication-provider:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
            security-attributes-provider:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
            users-roles:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
            onboarding:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
            tier1-gateway:
              podAnnotations:
                vault.security.banzaicloud.io/vault-skip-verify: "true"
        resourcePreset: low
    chart: authority
  destination:
    server: https://kubernetes.default.svc
    namespace: authority
