profile: authority

appConfig:
  springdoc:
    swagger-ui:
      # add other entries if you want to expose additional openapi
      urls:
        - url: /sapApi/openapi/securityattributesprovider-v1.yaml
          name: Security Attributes Provider Service V1
        - url: /onboardingApi/openapi/onboarding-v1.yaml
          name: Onboarding Service V1
        - url: /userApi/openapi/usersroles-v1.yaml
          name: Users & Roles Service V1
        - url: /identityApi/openapi/identityprovider-v1.yaml
          name: Identity Provider Service V1
        - url: /authApi/openapi/authenticationprovider-v1.yaml
          name: Authentication Provider Service V1
        - url: /openapi/tier1gateway-v1.yaml
          name: Application Info V1

  keycloak:
    app:
      realm: authority

  external-routes:
    spring-route-definitions:
      - id: fc-service
        uri: "http://xsfc-service:8081"
        predicates:
          - Path=/fc/**
        filters:
          - StripPrefix=1
      - id: schema-manager
        uri: "http://schema-manager-service:8085"
        predicates:
          - Path=/schema-manager/**
        filters:
          - StripPrefix=1
    public-urls:
      - path: "/schema-manager/**"

  jwt-configuration:
    primary:
      realm: authority
    applicant:
      realm: onboarding

  microservices-info:
    microservices:
      - name: users-roles
        internalUrl: "http://users-roles.authority.svc.cluster.local:8080/v1"
        detailUrl: "https://authority.be.authority.ds.helsinki.tfds.io/userApi/v1/"
      - name: sap
        internalUrl: "http://security-attributes-provider.authority.svc.cluster.local:8080/v1"
        detailUrl: "https://authority.be.authority.ds.helsinki.tfds.io/sapApi/v1/"
      - name: identity-provider
        internalUrl: "http://identity-provider.authority.svc.cluster.local:8080/v1"
        detailUrl: "https://authority.be.authority.ds.helsinki.tfds.io/identityApi/v1/"
      - name: onboarding
        internalUrl: "http://onboarding.authority.svc.cluster.local:8080/v1"
        detailUrl: "https://authority.be.authority.ds.helsinki.tfds.io/onboardingApi/v1/"
      - name: authentication-provider
        internalUrl: "http://authentication-provider.authority.svc.cluster.local:8080/v1"
        detailUrl: "https://authority.be.authority.ds.helsinki.tfds.io/authApi/v1/"
